version: '3.9'

networks:
  oil_network:
    driver: bridge

services:
  db:
    image: dockerhub.timeweb.cloud/library/mysql:8.0
    container_name: mysql_DB2
    environment:
      MYSQL_DATABASE: 'oilordersDB'
      MYSQL_USER: 'oilorder_admin'
      MYSQL_PASSWORD: 'oilpasswd'
      MYSQL_ROOT_PASSWORD: 'rootoilorderspsw'
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - oil_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "oilorder_admin", "-poilpasswd"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: oil-web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: 'oilorder_admin'
      DB_PASSWORD: 'oilpasswd'
      DB_NAME: 'oilordersDB'
      PYTHONIOENCODING: 'utf-8'
    networks:
      - oil_network
    restart: always
    volumes:
      - ./tmp:/app/tmp
      - ./templates:/app/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/catalog"]
      interval: 30s
      timeout: 10s
      retries: 3
